# Generated by Django 5.0.2 on 2024-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
