# Generated by Django 5.0.2 on 2024-02-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_current_progress_habit_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='is_complete',
        ),
    ]
