# Generated by Django 4.2.10 on 2024-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_egg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbirds',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
